### ISSUE TITLE
VS Code extension

### ISSUE THREAD

**Issue by antfu** [vitest-dev/vitest#107]
Similar to https://wallabyjs.com/

**Comment by mdbetancourt** [comment]
cool there is any job about this? i could help

**Comment by patak-dev** [comment]
Check the #vscode-ext channel in https://chat.vitest.dev @mdbetancourt, Anthony was already working on some prototypes

**Comment by N0tExisting** [comment]
I think this would also be useful <https://marketplace.visualstudio.com/items?itemName=hbenl.vscode-test-explorer>

**Comment by holtwick** [comment]
A quick solution could also be  https://github.com/firsttris/vscode-jest-runner if #838 could be fixed.

**Comment by antfu** [comment]
I have some progress at https://github.com/vitest-dev/vitest/tree/feat/vscode but I don't have enough time to continue on it currently. If anyone interested in it you can play with it and send improvements against that PR. Thanks.

**Comment by beorn** [comment]
> A quick solution could also be https://github.com/firsttris/vscode-jest-runner if #838 could be fixed.

It seems like it's already fixed?

I was naively hoping I could just set `jest.jestCommandLine` to `vitest` on  <https://marketplace.visualstudio.com/items?itemName=Orta.vscode-jest>, but it seems it requires some options that vitest doesn't support — it runs:

`jest --testLocationInResults --json --useStderr --outputFile /var/folders/.../jest_runner_....json --watch --no-coverage --reporters default --reporters /Users/.../.vscode/extensions/orta.vscode-jest-4.2.1/out/reporter.js --colors`

**Comment by holtwick** [comment]
@beorn Yes it is fixed an at least the "Run" action works fine for me. My only change to the settings was this one:

```json
"jestrunner.jestCommand": "pnpx vitest -r src --globals"
```

You might need to adopt it for your needs, usually the following setting should work:

```json
"jestrunner.jestCommand": "npx vitest"
```

**Comment by milkbump** [comment]
Another helpful reference test extension is [Playwright Test for Vscode](https://marketplace.visualstudio.com/items?itemName=ms-playwright.playwright). The work being done on Playwright Test makes me jealous as a Vitest user. 😂

**Comment by ThibaudMZN** [comment]
In what version is it possible to use `"jestrunner.jestCommand": "npx vitest"` ?
I'm still getting a `CACError: Unknown option '--testLocationInResults'`

**Comment by antfu** [comment]
Community solutions:
- https://marketplace.visualstudio.com/items?itemName=kingwl.vscode-vitest-runner by @kingwl
- https://marketplace.visualstudio.com/items?itemName=ZixuanChen.vitest-explorer by @zxch3n

**Comment by holtwick** [comment]
> In what version is it possible to use `"jestrunner.jestCommand": "npx vitest"` ? I'm still getting a `CACError: Unknown option '--testLocationInResults'`

@ThibaudMZN I use the latest version of https://marketplace.visualstudio.com/items?itemName=firsttris.vscode-jest-runner Only "Run" works, not "Debug". My specific setting is as follows, maybe this helps:

```
"jestrunner.jestCommand": "npx vitest -r src --globals",
```

**Comment by jtlapp** [comment]
> Community solutions:
> 
> * https://marketplace.visualstudio.com/items?itemName=kingwl.vscode-vitest-runner by @Kingwl

This one doesn't point to the line where the test failed or even indicate the line.

> * https://marketplace.visualstudio.com/items?itemName=ZixuanChen.vitest-explorer by @zxch3n

This one complains about not being able to find files in my svelte-kit installation and isn't running at all.

**Comment by zxch3n** [comment]
@jtlapp this plugin is still WIP. It takes some time to adapt to various project configures. May I ask how is your project setup?

**Comment by jtlapp** [comment]
> @milkbump The work being done on Playwright Test makes me jealous as a Vitest user. 😂

I installed vitest after failing to figure out how to get playwright working with browserless unit tests. I landed here for being unhappy with playwright. The only thing I see lacking in the vitest world is a fleshed-out VSCode extension.

**Comment by zxch3n** [comment]
@jtlapp It can point to the failed test case. The detail about which line goes wrong can be seen from the test output. 
<img width="1106" alt="image" src="https://user-images.githubusercontent.com/18425020/160147664-1f5fb3b5-9bed-4d25-91b9-37a0fb1796ef.png">

**Comment by jtlapp** [comment]
@zxch3n thanks for looking into it. It appears that you have code outputting the line, but that line doesn't always show. I don't recall ever seeing this line in the tests that errored with the postgres database running.

![no failure line](https://user-images.githubusercontent.com/138133/160149524-8d362614-c0fd-4eb0-b1ba-d87bfaf0758d.png)

I often tried to widen the right pain or to widen the VSCode window enough to see what was written into the right pane, but I never succeeded. So maybe it's just a UI issue?

**Comment by zxch3n** [comment]
@jtlapp NP 😄. You can right-click the red button beside the line number to peek error. And inside the left testing panel, you can click the `Show Output` at the top to see the full output from a test run. Maybe I can provide a code lens in the future to make it easier

**Comment by jtlapp** [comment]
> @jtlapp NP 😄. You can right-click the red button beside the line number to peek error. And inside the left testing panel, you can click the `Show Output` at the top to see the full output from a test run. Maybe I can provide a code lens in the future to make it easier

I didn't know about right-clicking that icon, but when I click "Peek Error" nothing happens -- I see no changes. And I can't find a "Show Output".

**Comment by jtlapp** [comment]
@zxch3n If I de-highlight the test case and click "Peek Error", it just re-highlights the entire test case, which contains many calls to `expect`.

**Comment by zxch3n** [comment]
<img width="399" alt="image" src="https://user-images.githubusercontent.com/18425020/160152734-68b41995-0e3c-4660-9bcb-8edecd4e1e3c.png">

`Peek Error` should display a window that shows the earlier test errors. This behavior is provided by VSCode Testing API.

**Comment by jtlapp** [comment]
@zxch3n Ah poo. That's not happening on my installation. VSCode 1.65.2, dated 2022-03-10.

**Comment by zxch3n** [comment]
@jtlapp I think this may be reported to vscode team. If you meet any other problem, let's discuss it at https://github.com/zxch3n/vitest-explorer/issues

**Comment by jtlapp** [comment]
@zxch3n I do want to point out to others seeing this thread that https://marketplace.visualstudio.com/items?itemName=ZixuanChen.vitest-explorer is still quite usable. When a test fails, I debug it to figure out which `expect` actually failed. Just a little extra work.

**Comment by sheremet-va** [comment]
Since we have [official VS Code extension](https://github.com/vitest-dev/vscode), this issue can be closed.
