### ISSUE TITLE
TypeError: Cannot read properties of null (reading 'isCE')

### ISSUE THREAD

**Issue by enrtama** [vitest-dev/vitest#1455]
### Describe the bug

Wen running `vitest --ui` I cannot visualize it due to an error: `TypeError: Cannot read properties of null (reading 'isCE')`

### Reproduction

Run `vitest --ui`

### System Info

```shell
"devDependencies": {
    "@babel/eslint-parser": "^7.18.2",
    "@types/node": "^17.0.41",
    "@vitejs/plugin-vue": "^2.3.3",
    "@vitest/ui": "^0.14.1",
    "@vue/test-utils": "^2.0.0",
    "@wdio/cli": "^7.20.1",
    "@wdio/local-runner": "^7.20.1",
    "@wdio/mocha-framework": "^7.20.0",
    "@wdio/spec-reporter": "^7.20.0",
    "@wdio/sync": "^7.20.1",
    "c8": "^7.11.3",
    "chromedriver": "^101.0.0",
    "eslint": "^8.17.0",
    "eslint-config-prettier": "^8.5.0",
    "eslint-plugin-vue": "^9.1.0",
    "eslint-plugin-webdriverio": "^1.0.1",
    "jsdom": "^19.0.0",
    "prettier": "^2.6.2",
    "pug": "^3.0.2",
    "pug-plain-loader": "^1.1.0",
    "sass": "^1.52.2",
    "ts-node": "^10.8.1",
    "typescript": "^4.5.4",
    "vite": "^2.9.9",
    "vite-plugin-eslint": "^1.6.1",
    "vitest": "^0.14.1",
    "vue-tsc": "^0.34.7",
    "wdio-chromedriver-service": "^7.3.2"
  }
```

### Used Package Manager

yarn

### Validations

- [X] Follow our [Code of Conduct](https://github.com/vitest-dev/vitest/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guidelines](https://github.com/vitest-dev/vitest/blob/main/CONTRIBUTING.md).
- [X] Read the [docs](https://vitest.dev/guide/).
- [X] Check that there isn't [already an issue](https://github.com/vitest-dev/vitest/issues) that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/vitest-dev/vitest/discussions) or join our [Discord Chat Server](https://chat.vitest.dev).
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by jannikegger** [comment]
Hey :) 
Same issue occurs to me. As an addition - in my console also the error `Cannot read properties of null (reading 'refs')` shows up. 

**Used Package Manager**
npm

**Comment by sheremet-va** [comment]
Fixed in 0.14.2

**Comment by jannikegger** [comment]
@enrtama did 0.14.2 fixed it for you? I just updated my version number and still getting the same error :(

**Comment by enrtama** [comment]
Yes, it's actually fixed for me!

**Comment by userquin** [comment]
> @enrtama did 0.14.2 fixed it for you? I just updated my version number and still getting the same error :(

You should include the 0.14.2 version on `vitest` and `@vitest/ui` dev dependencies.

https://stackblitz.com/edit/vitejs-vite-zzcmht?initialPath=__vitest__

**Comment by jannikegger** [comment]
@userquin argh that was dumb. while beeing in a meeting rush I totally forgot updating the ui dependency.
Many Thanks!
