### ISSUE TITLE
Invalid Date object will throw a TypeError in Vitest

### ISSUE THREAD

**Issue by dotnetCarpenter** [vitest-dev/vitest#2216]
### Describe the bug

The following two assertions should both succeed. But due to Vitest usage of `.toJSON()` on `Date` objects, the second line will fail with a `TypeError`.

```js
expect(NaN).toBe(NaN);
expect(new Date('not a date')).toBe(NaN);
```

The reason is that `.toJSON()` returns `undefined` on invalid Date objects.

```js
new Date('1990-01-01').toJSON();	// <- "1990-01-01T00:00:00.000Z"
new Date('foo bar').toJSON();		// <- null
```

On node 18.12 I get the following error:

```
TypeError: Cannot read properties of null (reading 'split')
```

On StackBlitz, I get:

```
TypeError: can't access property "split", dateObject.toJSON() is null
```

### Reproduction

```js
const { it, expect } = import.meta.vitest

it('Invalid Date is NaN', () => {
	expect (new Date ('not a date')).toBe (NaN)
})
```

### System Info

```shell
System:
    OS: Linux 5.10 Ubuntu 22.04.1 LTS 22.04.1 LTS (Jammy Jellyfish)
    CPU: (4) x64 Intel(R) Core(TM) i7-4510U CPU @ 2.00GHz
    Memory: 2.22 GB / 3.83 GB
    Container: Yes
    Shell: 5.1.16 - /bin/bash
  Binaries:
    Node: 18.12.0 - /usr/local/bin/node
    Yarn: 1.22.18 - ~/.yarn/bin/yarn
    npm: 8.19.2 - /usr/local/bin/npm
  npmPackages:
    vite: ^3.2.0 => 3.2.0 
    vitest: ^0.24.3 => 0.24.3
```

### Used Package Manager

npm

### Validations

- [X] Follow our [Code of Conduct](https://github.com/vitest-dev/vitest/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guidelines](https://github.com/vitest-dev/vitest/blob/main/CONTRIBUTING.md).
- [X] Read the [docs](https://vitest.dev/guide/).
- [X] Check that there isn't [already an issue](https://github.com/vitest-dev/vitest/issues) that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/vitest-dev/vitest/discussions) or join our [Discord Chat Server](https://chat.vitest.dev).
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by sheremet-va** [comment]
I think this is chai problem. The error comes from `loupe` package, according to stack trace. And is used by `chai`.

**Comment by dotnetCarpenter** [comment]
@sheremet-va I'm looking at _package.json_ but I can not see [Chai](https://github.com/chaijs/chai) as a dependency. I do not know pnpm but I do see Chai in [pnpm-lock.yaml](/vitest-dev/vitest/blob/main/pnpm-lock.yaml). Sorry, this might not be important. I am only trying to understand when/why Chai is injected into Vitest, in order to better understand where a fix for invalid dates should exist. I do not think it is obvious that it should be fixed in Loupe.

Could you check out https://github.com/chaijs/loupe/issues/58 and let us know what you think?

**Comment by sheremet-va** [comment]
> I'm looking at _package.json_ but I can not see [Chai](https://github.com/chaijs/chai) as a dependency

Not sure how you missed it: https://github.com/vitest-dev/vitest/blob/main/packages/vitest/package.json#L111

Vitest uses chai's `expect` with jest-compatible API.

> Could you check out https://github.com/chaijs/loupe/issues/58 and let us know what you think?

Not sure what I can say 😄 You issue is correct, I would expect it to be fixed on their side, and then we just upgrade.

**Comment by dotnetCarpenter** [comment]
@sheremet-va This has been fixed in [`loupe` 2.3.5](https://github.com/chaijs/loupe/releases/tag/v2.3.5) ([npm](https://www.npmjs.com/package/loupe/v/2.3.5)).

After some lengthy discussions (https://github.com/chaijs/loupe/issues/58#issuecomment-1303259185, https://github.com/chaijs/loupe/pull/59#discussion_r1013929212), we settled on `loupe` returning `"Invalid Date"` for an invalid `Date` object. So the test code has changed slightly to:

```js
const { it, expect } = import.meta.vitest

it('Invalid Date is "Invalid Date"', () => {
	expect (new Date ('not a date')).toBe ('Invalid Date')
})
```

**Comment by sheremet-va** [comment]
> So the test code has changed slightly to

`loupe` only affects error message. 

You should not get the internal error, when you call `expect(new Date('nod').toBe(NaN)`, anymore. But you will still get an error, because `toBe` is using `Object.is` for equality check.

Correct check would be:

```js
expect (new Date ('not a date').valueOf()).toBe(NaN)
```

Anyway, this issue can be closed, since Vitest 0.25.0 updated chai version to the one that has the fix.
