### ISSUE TITLE
Browser: Simple TypeScript test appearing+running in CLI mode but not Browser mode

### ISSUE THREAD

**Issue by frank-weindel** [vitest-dev/vitest#3286]
### Describe the bug

I have a simple TypeScript project with a single test file. The test file has only one test. When I run `vitest` in normal CLI mode the test is successfully run. When I run `vitest --browser "chrome"` the browser and vitest UI are launched but no tests are run.

### Reproduction

https://github.com/frank-weindel/vitest-3286-browser-typescript
- `npm install`
- Run `npm start` to see example app working.
  - You should see "1 + 1 = 2" in browser
- Run `npm run test` to see test for `add()` method running successfully
- Run `npm run test:browser` to see Chrome browser + Vitest UI launching but **no tests are run.**

### System Info

```shell
System:
    OS: macOS 12.2.1
    Shell: 5.8 - /bin/zsh
  Binaries:
    Node: 16.14.0 - ~/.nodenv/versions/16.14.0/bin/node
    npm: 8.3.1 - ~/.nodenv/versions/16.14.0/bin/npm
  Browsers:
    Chrome: 112.0.5615.137
```

### Used Package Manager

npm

### Validations

- [X] Follow our [Code of Conduct](https://github.com/vitest-dev/vitest/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guidelines](https://github.com/vitest-dev/vitest/blob/main/CONTRIBUTING.md).
- [X] Read the [docs](https://vitest.dev/guide/).
- [X] Check that there isn't [already an issue](https://github.com/vitest-dev/vitest/issues) that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/vitest-dev/vitest/discussions) or join our [Discord Chat Server](https://chat.vitest.dev).
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by tpluscode** [comment]
I think I have the same problem. The browser window opens but the network shows a hanging request for `http://localhost:63315/@id/vitest/utils`

**Comment by frank-weindel** [comment]
@tpluscode I actually had that problem originally. But I found a workaround. See #3124 and https://github.com/vitest-dev/vitest/issues/3124#issuecomment-1506335706 in particular.

**Comment by tpluscode** [comment]
Thanks!

**Comment by tpluscode** [comment]
Now the vitest UI loads but I get `504 Outdated Optimize Dep` for the request for `http://localhost:63315/@id/vitest/browser`

**Comment by tpluscode** [comment]
By experimenting blindly with the `opimizeDeps` options, I found that the `504` response is solved by setting `noDiscovery: true`

The however, I sometimes get an error like:

```
SyntaxError: The requested module '/node_modules/concordance/index.js?v=ea45bb1f' does not provide an export named 'default'
```

**Comment by userquin** [comment]
Should be fixed in next 0.31.0 release, check `optimizedDeps` in #3190 (you need to remove `.vite` folder)

**Comment by abrowne2** [comment]
This is similar to my experience; removing the .vite folder does not seem to fix the issue either. 

If I run `vitest --ui` my simple typescript tests are identified and pass, but if I run `vitest --browser`, with the same tests present, they show as `No test suite found in file`.

**Comment by sheremet-va** [comment]
This should be fixed now.
