### ISSUE TITLE
Coverage report not including any files

### ISSUE THREAD

**Issue by robcaldecott** [vitest-dev/vitest#378]
### Describe the bug

I created a simple Vite React TS app that uses testing-library, etc. but running `vitest --coverage` does not work and no files are included:

```
$ npm run coverage

> vite-project@0.0.0 coverage
> vitest --run --coverage


 RUN  /Users/rob/vite-project

 √ src/App.test.tsx (1)

Test Files  1 passed (1)
     Tests  1 passed (1)
      Time  4.53s (in thread 151ms, 3007.08%)

----------|---------|----------|---------|---------|-------------------
File      | % Stmts | % Branch | % Funcs | % Lines | Uncovered Line #s 
----------|---------|----------|---------|---------|-------------------
All files |       0 |        0 |       0 |       0 |                   
----------|---------|----------|---------|---------|-------------------
```

### Reproduction

https://github.com/robcaldecott/vitest-coverage

### System Info

```shell
System:
    OS: macOS Mojave 10.14.6
    CPU: (4) x64 Intel(R) Core(TM) i5-6360U CPU @ 2.00GHz
    Memory: 373.21 MB / 8.00 GB
    Shell: 3.2.57 - /bin/bash
  Binaries:
    Node: 16.13.1 - /usr/local/bin/node
    Yarn: 1.19.1 - /usr/local/bin/yarn
    npm: 8.1.2 - /usr/local/bin/npm
    Watchman: 4.9.0 - /usr/local/bin/watchman
  Browsers:
    Chrome: 96.0.4664.110
    Firefox: 61.0.1
    Safari: 14.1.2
  npmPackages:
    @vitejs/plugin-react: ^1.0.7 => 1.1.3 
    vite: ^2.7.2 => 2.7.10 
    vitest: ^0.0.124 => 0.0.124
```

### Used Package Manager

npm

### Validations

- [X] Follow our [Code of Conduct](https://github.com/vitest-dev/vitest/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guidelines](https://github.com/vitest-dev/vitest/blob/main/CONTRIBUTING.md).
- [X] Read the [docs](https://vitest.dev/guide).
- [X] Check that there isn't [already an issue](https://github.com/vitest-dev/vitest/issues) that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/vitest-dev/vitest/discussions) or join our [Discord Chat Server](https://chat.vitest.dev).
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by michael-observerly** [comment]
I can confirm this is also happening. In a vanilla-ts project.

**Comment by grixu** [comment]
I also confirm this bug, in vue-ts project

**Comment by michael-observerly** [comment]
@robcaldecott This seems to now be fixed in version > 0.1.

**Comment by robcaldecott** [comment]
Still not working for me for any `.tsx` files in the `src` folder.

**Comment by Demivan** [comment]
Fixed in [v0.2.0](https://github.com/vitest-dev/vitest/releases/tag/v0.2.0)

Tested on https://github.com/robcaldecott/vitest-coverage

```
 √ src/App.test.tsx (1)

Test Files  1 passed (1)
     Tests  1 passed (1)
      Time  1.74s (in thread 82ms, 2127.31%)

----------|---------|----------|---------|---------|-------------------
File      | % Stmts | % Branch | % Funcs | % Lines | Uncovered Line #s 
----------|---------|----------|---------|---------|-------------------
All files |     100 |      100 |     100 |     100 |                   
 App.tsx  |     100 |      100 |     100 |     100 |                   
----------|---------|----------|---------|---------|-------------------
```
