### ISSUE TITLE
Typescript build failes due to chai default export

### ISSUE THREAD

**Issue by Destiner** [vitest-dev/vitest#596]
### Describe the bug

When running `tsc`, the build fails due to the typing issue inside Vitest:
```
node_modules/vitest/dist/index.d.ts:5:18 - error TS2305: Module '"chai"' has no exported member 'default'.

5 export { assert, default as chai, should } from 'chai';
```

### Reproduction

Repo: https://github.com/Destiner/vitest-ts
Action run result: https://github.com/Destiner/vitest-ts/runs/4895155132

### System Info

```shell
System:
    OS: macOS 11.6
    CPU: (4) x64 Intel(R) Core(TM) i5-7267U CPU @ 3.10GHz
    Memory: 53.82 MB / 8.00 GB
    Shell: 5.8 - /bin/zsh
  Binaries:
    Node: 16.11.1 - /usr/local/bin/node
    Yarn: 1.22.10 - /usr/local/bin/yarn
    npm: 8.0.0 - /usr/local/bin/npm
  Browsers:
    Chrome: 97.0.4692.99
    Firefox: 95.0.2
    Safari: 15.0
```

### Used Package Manager

npm

### Validations

- [X] Follow our [Code of Conduct](https://github.com/vitest-dev/vitest/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guidelines](https://github.com/vitest-dev/vitest/blob/main/CONTRIBUTING.md).
- [X] Read the [docs](https://vitest.dev/guide).
- [X] Check that there isn't [already an issue](https://github.com/vitest-dev/vitest/issues) that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/vitest-dev/vitest/discussions) or join our [Discord Chat Server](https://chat.vitest.dev).
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by Destiner** [comment]
I know there was another issue related to that (#510), I'm opening a new one since the old one was closed by the author, and I believe the issue still persists.

**Comment by cbxp** [comment]
I have debugged a similar issue and it seems that it only fails for the first time, and works with subsequent runs.

The reason is that at first run of tests, Vite discovers new node_modules (chai, etc) and starts bundling them, but for some reason tests still get executed with unconverted packages to es6 modules.

Workaround is to tell Vite to pre-bundle test packages:
```
  optimizeDeps: {
    include: isTest ? ['@testing-library/svelte', 'chai', 'sinon', 'sinon-chai'] : undefined
  },
```

Then tests work also on the first run

**Comment by Destiner** [comment]
Fixed by upgrading to `0.3.4` and setting `compilerOptions.esModuleInterop` to `true` in tsconfig.json.

**Comment by o-az** [comment]
I'm still getting this
![CleanShot 2022-05-06 at 17 28 21](https://user-images.githubusercontent.com/23618431/167223920-c1a7ed2d-9a94-48dd-8aa0-84d09299668d.png)

**Comment by sheremet-va** [comment]
Try passing "--skipLibCheck" to tsc
