### ISSUE TITLE
Updating snapshots doesn't remove obsolete ones

### ISSUE THREAD

**Issue by uicrafts** [vitest-dev/vitest#686]
### Describe the bug

For a `.tsx` file with snapshot tests, if a new snapshot is added and later removed this then becomes an "obsolete" snapshot. In the interactive terminal when using Vitest's watch mode, pressing `u` to update snapshots does not remove obsolete ones. In Jest, `u` does two things: update existing snapshots, and remove obsolete ones.

<img width="481" alt="image" src="https://user-images.githubusercontent.com/4595734/152656873-5e120a4b-e1c3-4694-971c-086b3916ccc7.png">

When pressing `u` Vitest prints `Re-running tests... [ update snapshot ]` but nothing happns.
<img width="469" alt="image" src="https://user-images.githubusercontent.com/4595734/152657030-5b782a19-d679-41c2-bbb0-c027697fcf40.png">

The workaround is to delete the obsolete snapshots manually.

### Reproduction

Repro: https://stackblitz.com/edit/node-jhjpur?file=src%2Fcomponents%2FButton.test.tsx

### System Info

```shell
System:
    OS: macOS 11.6.2
    CPU: (12) x64 Intel(R) Core(TM) i7-9750H CPU @ 2.60GHz
    Memory: 43.79 MB / 16.00 GB
    Shell: 5.8 - /bin/zsh
  Binaries:
    Node: 16.13.0 - /usr/local/bin/node
    Yarn: 1.22.17 - ~/.yarn/bin/yarn
    npm: 8.1.2 - /usr/local/bin/npm
    Watchman: 4.9.0 - /usr/local/bin/watchman
  Browsers:
    Chrome: 98.0.4758.80
    Edge: 98.0.1108.43
    Firefox: 96.0.3
    Firefox Developer Edition: 79.0
    Safari: 15.3
    Safari Technology Preview: 15.4
  npmPackages:
    @vitejs/plugin-react: ^1.1.4 => 1.1.4
    vite: ^2.7.13 => 2.7.13
    vitest: ^0.2.7 => 0.2.7
```
```


### Used Package Manager

yarn

### Validations

- [X] Follow our [Code of Conduct](https://github.com/vitest-dev/vitest/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guidelines](https://github.com/vitest-dev/vitest/blob/main/CONTRIBUTING.md).
- [X] Read the [docs](https://vitest.dev/guide).
- [X] Check that there isn't [already an issue](https://github.com/vitest-dev/vitest/issues) that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/vitest-dev/vitest/discussions) or join our [Discord Chat Server](https://chat.vitest.dev).
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by konpeki622** [comment]
I have the same issue, which is also mentioned at #595 . Here is my test result: https://github.com/originjs/origin.js/runs/5119787485?check_suite_focus=true
These snapshot failures still happened though I have run `vitest run -u`.

**Comment by konpeki622** [comment]
Upgrading to version 0.3.2 works for me.

**Comment by sheremet-va** [comment]
Cannot reproduce on the latest version. @uicrafts can you confirm it is fixed?

**Comment by uicrafts** [comment]
Unfortunately, I can still reproduce this on `0.5.0`. 

See here: https://stackblitz.com/edit/node-qtcaat?file=src%2Fcomponents%2FButton.test.tsx

**Comment by capaj** [comment]
still reproducable on 0.9.4.
This one should really get fixed before 1.0.0

**Comment by cpakken** [comment]
Same for me, obsolete snapshot still remains after updating snapshots

**Comment by moltar** [comment]
Seeing this in `0.12.9` as well.

Interestingly that it did detect them:

```
 Snapshots  7 written
            7 obsolete
```

But didn't do anything about them.

**Comment by Antoine-Regembal** [comment]
Same issue here with vitest 0.13.1

**Comment by uicrafts** [comment]
@antfu Looks like this is still an issue on `0.14.1`, FYI.

**Comment by jannikegger** [comment]
yep, can confirm that this is still an open issue for `0.14.2`

**Comment by gkiely** [comment]
Confirmed this is still an issue and also seeing no updates for failing snapshots.

Example repo here: https://github.com/gkiely/vite-app-rtl

Steps to reproduce:
```
npm install
npm test

> Press u
> Doesn't update
```

**Comment by mathieudehaeck** [comment]
Same issue using `0.15.1`

**Comment by gkiely** [comment]
Thanks for fixing this @sheremet-va!

**Comment by macabeus** [comment]
How to run the update a snapshot without removing the obsolete ones?
