### ISSUE TITLE
`Channel closed` error as of recent version of Vitest

### ISSUE THREAD

**Issue by breadadams** [vitest-dev/vitest#8201]
### Describe the bug

Apologies beforehand, vague bug report incoming...

As of a _recent_ Vitest update (potentially between `v3.1.4` and `v3.2.3`) we're seeing the following error in CI, where it appears the channel is closed before our tests have finished running:

```
⎯⎯⎯⎯ Unhandled Rejection ⎯⎯⎯⎯⎯
Error: Channel closed
 ❯ target.send node:internal/child_process:753:16
 ❯ ProcessWorker.send ../../node_modules/tinypool/dist/index.js:140:41
 ❯ MessagePort.<anonymous> ../../node_modules/tinypool/dist/index.js:146:62
 ❯ [nodejs.internal.kHybridDispatch] node:internal/event_target:831:20
 ❯ MessagePort.<anonymous> node:internal/per_context/messageport:23:28

⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯
Serialized Error: { code: 'ERR_IPC_CHANNEL_CLOSED' }
```

Opening this issue hoping that maybe someone could point me in the right direction.

### Reproduction

Unsure how to reproduce 😬 

### System Info

```shell
Vitest version: `v3.2.3`


System:
  OS: Linux 6.11 Ubuntu 22.04.5 LTS 22.04.5 LTS (Jammy Jellyfish)
  CPU: (16) x64 AMD EPYC 7763 64-Core Processor
  Memory: 60.17 GB / 62.80 GB
  Container: Yes
  Shell: 5.1.16 - /bin/bash
Binaries:
  Node: 20.19.2 - /__t/node/20.19.2/x64/bin/node
  Yarn: 1.22.22 - /usr/bin/yarn
  npm: 10.8.2 - /__t/node/20.19.2/x64/bin/npm
```

### Used Package Manager

yarn

### Validations

- [x] Follow our [Code of Conduct](https://github.com/vitest-dev/vitest/blob/main/CODE_OF_CONDUCT.md)
- [x] Read the [Contributing Guidelines](https://github.com/vitest-dev/vitest/blob/main/CONTRIBUTING.md).
- [x] Read the [docs](https://vitest.dev/guide/).
- [x] Check that there isn't [already an issue](https://github.com/vitest-dev/vitest/issues) that reports the same bug to avoid creating a duplicate.
- [x] Check that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/vitest-dev/vitest/discussions) or join our [Discord Chat Server](https://chat.vitest.dev).
- [x] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by breadadams** [comment]
After further inspection I'm leaning to believe this appeared after we updated from 3.1.4 to 3.2.1, where `tinypool` was bumped to `1.1.0` (in https://github.com/vitest-dev/vitest/pull/8061).

Downgrading on our end to see if we can confirm.

**Comment by AriPerkkio** [comment]
You can also update the transitive dependency of `tinypool` to `1.1.0` when using `vitest@3.1.4`. 

Without reproduction there's not much to do.

**Comment by breadadams** [comment]
True @AriPerkkio, however since we don't have other packages installing `tinypool` (nor install it ourselves) we've just had the same version as Vitest installed.

I've downgraded tinypool to `1.0.2` (staying on latest version of Vitest) and ran a comparison in our CI, executing unit tests 60 times across a monorepo of 21 projects:

- On `1.0.2`: 0 failures
- On `1.1.0`: 18 failures

I understand there isn't much that can be done without a repro, which is something I just cannot provide. This is a pretty large project where we're getting the error and I can't single out what's causing it.

However, a couple of things:

1. I'm pretty sure something in the [`1.1.0` release](https://github.com/tinylibs/tinypool/releases/tag/v1.1.0) has caused this (personally can't see what). Since I see you're the author of a a couple of the additions there maybe you have an idea?
2. If you have any suggestions on how I could potentially provide a repro I'd be more than happy to.

Thanks

**Comment by AriPerkkio** [comment]
As Vitest does not pin the version of Tinypool, you can use the `tinypool@1.1.0` even with `vitest@2`. You can update the transitive dependencies in your package manager's lockfile.

It would be interesting to see if your tests crash with `vitest@3.1.4` and `tinypool@1.1.0` (or even `1.1.1`). My guess is that the Tinypool release is not causing this, but it's rather https://github.com/vitest-dev/vitest/pull/7704 causing some condition in your test cases.

The error itself doesn't make sense - something is trying to commmunicate with the IPC after port was closed. It's always closed after test file has finished running and worker is terminated. 🤷
You could try if `pool: 'threads'` works any better.

**Comment by doctolivier** [comment]
Hey there, I have exactly the same error on my work CI since I've updated from `vitest@3.1.4` to `vitest@3.2.4`
On my side, only our custom MacOS CI crash with this error. Windows and Linux CI work fine.
I suppose it's some specific tests who are launched on MacOS that fail. 
The `pool: 'threads'` didn't help

**Comment by NicholyHabs** [comment]
Hi there 👋🏼 , 

My team and I have experienced the same error above. Pinning to  `vitest@3.1.4` and `tinypool@1.1.1` resolved the issues. 

FWIW, it only broke tests on MacOS, we never saw the test failure in our CICD Build servers.

**Comment by enisdenjo** [comment]
Experiencing the same error on my side. Fails in macOS but running smoothly with CI.

**Comment by enisdenjo** [comment]
For me it was a [node-canvas](https://github.com/Automattic/node-canvas). I was setting the height on an instance of canvas and Node would crash with the error as in the description.

Updating canvas to latest fixed the issue, fixed in https://github.com/Automattic/node-canvas/issues/2520.

**Comment by luchillo17** [comment]
Why is this `Not planned` if we see at least 4 people have the issue? (I counted all but @AriPerkkio and the bot, as it seem people are still not used to using 👍 reaction emoji to count impacted people).

**Comment by dperetti** [comment]
Count me in.
<img width="902" alt="Image" src="https://github.com/user-attachments/assets/a7c929ff-34cf-44d0-bf12-c83614964572" />

**Comment by luchillo17** [comment]
In WSL when it happens the vitest processes do not die with the main one, and instead hog ram, to the point I have to kill the processes with `pkill -f vitest` or else it crashes the WSL2 instance.

**Comment by jsphstls** [comment]
This issue is absolutely not resolved despite the closed status. Apologies @sheremet-va, but I feel the need to raise this to you given the chance that some level of automation is prematurely closing the status of an active issue.

**Comment by AriPerkkio** [comment]
It was closed due to missing reproduction. Any updates on that? https://github.com/vitest-dev/vitest/issues/8201#issuecomment-2993459996

**Comment by sheremet-va** [comment]
I will keep this open, but we cannot do anything if there is no reproduction

**Comment by JustinBeckwith** [comment]
Apologies for not having a pithy repro - but I'm running into this as well.  I'm migrating my codebase from mocha => vitest, and seeing inconsistent, somewhat random "Error: channel closed" in CI.  It appears to happen far more frequently in GitHub actions, which makes me wonder if it's a memory issue.  

If it's at all helpful, here's the github actions runs where I'm seeing it:  https://github.com/JustinBeckwith/linkinator/actions/runs/16130420367/job/45516589956?pr=673

I'll keep seeing if I can create a smaller repro that's easier to track down.

**Comment by JustinBeckwith** [comment]
Somewhat randomly in local development, I'm also seeing:

```
Assertion failed: (!uv__io_active(&stream->io_watcher, POLLIN | POLLOUT)), function uv__stream_destroy, file src/unix/stream.c, line 456.

⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯ Unhandled Rejection ⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯
Error: Channel closed
 ❯ target.send node:internal/child_process:753:16
 ❯ ProcessWorker.send node_modules/tinypool/dist/index.js:140:41
 ❯ MessagePort.<anonymous> node_modules/tinypool/dist/index.js:149:62
 ❯ [nodejs.internal.kHybridDispatch] node:internal/event_target:827:20
 ❯ MessagePort.<anonymous> node:internal/per_context/messageport:23:28

⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯
Serialized Error: { code: 'ERR_IPC_CHANNEL_CLOSED' }
```

**Comment by AriPerkkio** [comment]
> `Assertion failed: (!uv__io_active(&stream->io_watcher, POLLIN | POLLOUT)), function uv__stream_destroy, file src/unix/stream.c, line 456.`

This looks familiar: https://github.com/mswjs/msw/issues/2537#issuecomment-3034448679. Looks like this happens with older version of Vitest too. 


If the `node:child_process` fork crashes unexpectedly, it is expected to see this error. We should probably attach the test filenames in error message here:

https://github.com/vitest-dev/vitest/blob/c1f78d2adc78ef08ef8b61b0dd6a925fb08f20b6/packages/vitest/src/node/pools/forks.ts#L140-L163

**Comment by weston-ob** [comment]
fwiw, I tracked this issue in my project back to a bad import from `node:test` instead of `vitest`. Adding just this code block to my setup file causes the issue. Not sure if this is the mistake others made or if it helps point towards a broader issue, hope it helps!

```
import { afterEach as afterEachNode } from 'node:test';

afterEachNode();
```

**Comment by mallowigi** [comment]
Happens to me as well. Downgrading to 3.1.4 fixed the issue

Edit: Didn't fix the issue completely apparently

**Comment by michaelholstdev** [comment]
We have the same Problem:

<img width="1111" height="309" alt="Image" src="https://github.com/user-attachments/assets/a7981258-ffa1-4c69-8611-7481325316c5" />

added this to our `setupTests.ts`, to see in which area of tests/code this error occurs:

```
process.on('unhandledRejection', (reason) => {
  console.log(reason);
  process.exit(1);
});
```

It happens randomly, but when its always at the same spot.

<img width="289" height="330" alt="Image" src="https://github.com/user-attachments/assets/ea06792c-c2a1-4ff2-b100-bebbac9bc9a4" />

But before Ive added the process block, we got randomly errors like "Reference Error localstorage is not defined" or "Reference Error Request is not defined" - but also randomly, sometimes it occurs, with a random error message that we should check setIntervals/setTimeouts and async/await.

**Comment by carlolol** [comment]
running `npm test` reproduces this on my end. running `npm run test` completely avoids the issue, but I could see spike to CPU usage either way.
```
System:
    OS: macOS 15.5
    CPU: (10) arm64 Apple M1 Max
    Memory: 22.12 GB / 64.00 GB
    Shell: 5.9 - /bin/zsh
  Binaries:
    Node: 24.4.1 - ~/.nvm/versions/node/v24.4.1/bin/node
    Yarn: 1.22.22 - /usr/local/bin/yarn
    npm: 11.5.2 - ~/.nvm/versions/node/v24.4.1/bin/npm
    pnpm: 9.12.1 - /usr/local/bin/pnpm
  Browsers:
    Brave Browser: 138.1.80.125
    Chrome: 138.0.7204.184
    Edge: 138.0.3351.121
    Safari: 18.5
  npmPackages:
    @vitejs/plugin-vue: ^6.0.1 => 6.0.1
    @vitest/coverage-v8: ^3.2.4 => 3.2.4
    @vitest/eslint-plugin: ^1.3.4 => 1.3.4
    vite: ^7.0.6 => 7.0.6
    vitest: ^3.2.4 => 3.2.4
```

**Comment by daryawood** [comment]
We experienced the same issue across multiple frontend packages and couldn’t identify the root cause. We tried several approaches: clearing timeouts, adjusting debounces, tweaking pool settings, upgrading react-testing-library dependencies, changing concurrency. But the only thing that resolved it was downgrading to 3.1.4.

**Comment by atomiks** [comment]
In my case, it seemed to be related to passing a React event into `vi.fn()`. 

[I linked the fix](https://github.com/atomiks/base-ui/commit/fa0889e091715169b24a5d3dc0a462a1bc939400) above in case it helps.  I wasn't able to quickly reproduce it with a simple component and passing an `onClick` event into it though.

**Comment by luchillo17** [comment]
> As Vitest does not pin the version of Tinypool, you can use the `tinypool@1.1.0` even with `vitest@2`. You can update the transitive dependencies in your package manager's lockfile.
> 
> It would be interesting to see if your tests crash with `vitest@3.1.4` and `tinypool@1.1.0` (or even `1.1.1`). My guess is that the Tinypool release is not causing this, but it's rather [#7704](https://github.com/vitest-dev/vitest/pull/7704) causing some condition in your test cases.
> 
> The error itself doesn't make sense - something is trying to commmunicate with the IPC after port was closed. It's always closed after test file has finished running and worker is terminated. 🤷 You could try if `pool: 'threads'` works any better.

In my case overriding tinypool did work, but have to be specifically `v1.0.2`:
```json
{
  // package.json
  "overrides": {
    "tinypool": "1.0.2"
  },
}
```

**Comment by jishi** [comment]
Just to give some ideas for people ending up here, I got the same error but the error wasn't related to vitest or tinypool at all. It was the fact that I had a native npm module that was pre-compiled for the wrong C-lib (glibc vs musl) so I assume the test process abruptly crashed without any chance to output whatever happened (hence the IPC channel closed since I assume that's what forwarding the child process output streams?).

I also got different behavior between amd64 vs arm64 architecture, where amd64 actually outputted some missing ld-linux.x86_64.so.2 library which gave it away. 

Unlikely that you'd have the exact same problem as me (corrupted .pnpm-store due to re-use between different docker images debian vs alpine) BUT the fact that you get the `ERR_IPC_CHANNEL_CLOSED` when your test-runner just insta-crashes might point you in the right direction. 

Running the tests as a single fork/thread might give you a better hint, if you can avoid IPC altogether.
