### ISSUE TITLE
Do not create multiple environments in the same worker

### ISSUE THREAD

**Issue by yjaaidi** [vitest-dev/vitest#8919]
### Clear and concise description of the problem

As mentioned previously by @janpot https://github.com/vitest-dev/vitest/issues/8478, recreating an environment in the same worker can cause issues with many libraries such as `@testing-library/dom` or `@angular/cdk` as they hold the DOM instance of the first test they meet.

This only happens when using `isolate: false` and `maxWorkers > 1`. 

The issue persists in v4 (i.e. 4.0.6)

### Suggested solution

As mentioned in the previous issue: https://github.com/vitest-dev/vitest/issues/8478#issuecomment-3421518590, this can be fixed by changing the spec grouping logic and splitting non-isolated tests in as many groups as `maxWorkers`.

If this is a suitable solution, I am willing to submit a PR.

### Alternative

If I am missing something and the suggested solution is not suitable, then Vitest should log a warning if the user explicitly provides `isolate: false` and `maxWorkers > 1` in the same options object.

### Validations

- [x] Follow our [Code of Conduct](https://github.com/vitest-dev/vitest/blob/main/CODE_OF_CONDUCT.md)
- [x] Read the [Contributing Guidelines](https://github.com/vitest-dev/vitest/blob/main/CONTRIBUTING.md).
- [x] Read the [docs](https://vitest.dev/guide/).
- [x] Check that there isn't already an issue that request the same feature to avoid creating a duplicate.

**Comment by sheremet-va** [comment]
There is already a PR for this - https://github.com/vitest-dev/vitest/pull/8915

**Comment by yjaaidi** [comment]
Always ahead! ⚡️🚀
_Sorry for the noise then. I checked for issues first but didn't think of checking pending PRs 😊._

**Comment by AriPerkkio** [comment]
Fixed by https://github.com/vitest-dev/vitest/pull/8915

**Comment by arty-name** [comment]
I think it didn’t fix it. I don’t have a 100% certainty that my issue is caused by that, but starting with 4.0.5 I see state leaking between test files, and it still happens with 4.0.7 which supposedly includes the fix.

**Comment by AriPerkkio** [comment]
@arty-name the https://github.com/vitest-dev/vitest/pull/8915 is not related to fixing any state leaking. It's intended to only change how `isolate: false` works, which already leaks state.

Please open separate issue with reproduction.

**Comment by arty-name** [comment]
I’ve opened https://github.com/vitest-dev/vitest/issues/8944
